/**
 * @description
 */ 
public class DealerTrack_Loan 
{
    /**
     * @description
     */ 
    public String CashSellingPrice { get; set; }
    
    /**
     * @description
     */ 
    public String SalesTax { get; set; }
    
     /**
     * @description
     */ 
    public String Title { get; set; }
    
    /**
     * @description
     */        
    public String CashDown { get; set; }
    
    /**
     * @description
     */ 
    public String Rebate { get; set; }
    
    /**
     * @description
     */ 
    public String CreditLifeIns { get; set; }
    
    /**
     * @description
     */ 
    public String Term { get; set; }
    
    /**
     * @description
     */ 
    public String AcquisitionFees { get; set; }
    
    /**
     * @description
     */ 
    public String InvoiceAmount { get; set; }
    
    /**
     * @description
     */ 
    public String Warranty { get; set; }
    
    /**
     * @description
     */ 
    public String MSRP { get; set; }
    
    /**
     * @description
     */ 
    public String RequestedAPR { get; set; }
    
    /**
     * @description
     */ 
    public String AmountRequesting  { get; set; }
    
    /**
     * @description
     */ 
    public String EstimatedPayment { get; set; }
    
    /**
     * @description
     */ 
    public String MonthlyPayment { get; set; }
    
    /**
     * @description
     */ 
    public String CreditType { get; set; }   
    
    /**
     * @description
     */ 
    public String ApplicantType { get; set; }
    
    /**
     * @description
     */ 
    public String UnpaidBalance { get; set; }
    
    /**
     * @description
     */ 
    public String AccHealthInsurance { get; set; }
    
    /**
     * @description
     */ 
    public String OtherFinanceFees { get; set; }
    
    /**
     * @description
     */ 
    public String Gap { get; set; }
    
    /**
     * @description
     */ 
    public String OtherFees { get; set; }
    
    /**
     * @description
     */ 
    public String WholesaleBookSource { get; set; }
    
    /**
     * @description
     */ 
    public String WholesaleCondition { get; set; }
    
    /**
     * @description
     */ 
    public String WholesaleValueType { get; set; }
    
    /**
     * @description
     */ 
    public String WholesaleValue { get; set; }
    
    /**
     * @description
     */ 
    public String NetTrade { get; set; }
    
    /**
     * @description
     */ 
    public String CustomerNegotiatedPrice { get; set; }
    
    /**
     * @description
     */ 
    public String DealerNegotiatedPrice  { get; set; }
}