/**
 * DealerTrackEnumProperties
 * @description
 */
public class DealerTrackEnumProperties 
{
	/**
	 * @description
	 */
	public string LeadType { get; set; }
	
	/**
	 * @description
	 */
	public string FinanceMethod { get; set; }
	
	/**
	 * @description
	 */
	public string ApplicantState { get; set; }
	
	/**
	 * @description
	 */
	public string ApplicantPreviousState { get; set; }
	
	/**
	 * @description
	 */
	public string HousingStatus { get; set; }
	
	/**
	 * @description
	 */
	public string EmploymentStatus { get; set; }
	
	/**
	 * @description
	 */
	public string PresentEmployerState { get; set; }
	
	/**
	 * @description
	 */
	public string PreviousEmployerState { get; set; }

	/**
	 * @description
	 */
	public string CoAppRelationship { get; set; }
	
	/**
	 * @description
	 */
	public string CoApplicantState { get; set; }
	
	/**
	 * @description
	 */
	public string CoAppPreviousState { get; set; }
	
	/**
	 * @description
	 */
	public string CoAppHousingStatus { get; set; }
	
	/**
	 * @description
	 */
	public string CoAppEmploymentStatus { get; set; }
	
	/**
	 * @description
	 */
	public string CoAppPresentEmployerState { get; set; }
	
	/**
	 * @description
	 */
	public string CoAppPreviousEmployerState { get; set; }	
}