#theme: jekyll-theme-midnight
#remote_theme: pawamoy/jekyll-readthedocs
#remote_theme: pmarsceil/just-the-docs
#good: remote_theme: carlosperate/jekyll-theme-rtd
#loads but messy: remote_theme: allejo/jekyll-docs-theme
#remote_theme: CloudCannon/edition-jekyll-template
#good: remote_theme: marella/jekyll-theme-documentation
remote_theme: rundocs/jekyll-theme-docsify