#theme: jekyll-theme-midnight
#remote_theme: pawamoy/jekyll-readthedocs
#remote_theme: pmarsceil/just-the-docs
#good: remote_theme: carlosperate/jekyll-theme-rtd
remote_theme: allejo/jekyll-docs-theme