#theme: jekyll-theme-midnight
#remote_theme: pawamoy/jekyll-readthedocs
#remote_theme: pmarsceill/just-the-docs
#good: remote_theme: carlosperate/jekyll-theme-rtd
#loads but messy: remote_theme: allejo/jekyll-docs-theme
#remote_theme: CloudCannon/edition-jekyll-template
#good: remote_theme: marella/jekyll-theme-documentation
#good: remote_theme: rundocs/jekyll-theme-docsify
#remote_theme: 
pixeldroid/programming-pages
#ok: remote_theme: rundocs/jekyll-rtd-theme