# This is a basic workflow to update class documentation within Readme.com

name: ReadMe Sync

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "rdme" ]
  pull_request:
    branches: [ "rdme" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install and build rdme deps
        run: npm ci && npm run build

      # Let's dynamically update our docs with the latest version of rdme!
      # Note that these next three steps are not required
      # in order to sync your docs to ReadMe.

      # First, we run a script that sets a few outputs:
      # our package version and our Node.js version.
      - name: Retrieve version values
        id: rdme-version
        run: ./bin/set-version-output

      # Next, we use this output to do a few find/replaces!
      - name: Find and replace Node.js version placeholders
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'NODE_VERSION'
          replace: ${{ steps.rdme-version.outputs.NODE_VERSION }}
          regex: false
          include: documentation/*

      - name: Find and replace `rdme` version placeholders
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'RDME_VERSION'
          replace: ${{ steps.rdme-version.outputs.RDME_VERSION }}
          regex: false
          include: documentation/*

      # And finally, with our updated documentation,
      # we run the `rdme` GitHub Action to sync the Markdown file
      # in the `documentation` directory.
      # Here's the page we're syncing: https://docs.readme.com/docs/rdme

      # First we're going to perform a dry run of syncing process.
      # We do this on every push to ensure that an actual sync will work properly
      - name: Sync docs to ReadMe (dry run)
        uses: ./
        with:
          rdme: docs ./documentation --key=${{ secrets.README_DEVELOPERS_API_KEY }} --version=2.0 --dryRun

      # And finally, we perform an actual sync to ReadMe if we're on the main branch
      - name: Sync docs to ReadMe
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
        # We use the `main` branch as ref for GitHub Action
        # This is NOT recommended, as it can break your workflows without notice!
        # We recommend specifying a fixed version, i.e. @7.0
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@main
        with:
          rdme: docs ./documentation --key=${{ secrets.README_DEVELOPERS_API_KEY }} --version=2.0
